import { 
  ContentManager, 
  ContentManagerRoadmap, 
  ContentManagerStats, 
  RoadmapVersion,
  RoadmapNodeDTO,
  RoadmapEdgeDTO,
  NodeContentItemDTO,
  ContentManagerRoadmapDetail,
  NodeDifficulty,
  EdgeType
} from './types';
import { PaginatedResponse } from '@/features/roadmaps/api/types';

export const MOCK_CONTENT_MANAGER: ContentManager = {
  id: 'cm-001',
  name: 'Sarah Johnson',
  email: 'sarah.johnson@studysense.com',
  avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
  learningSubjectId: 1,
  learningSubjectName: 'Frontend Development',
  categoryId: 1,
  categoryName: 'Programming',
  joinedAt: '2024-01-15T10:00:00Z',
};

export const MOCK_STATS: ContentManagerStats = {
  totalRoadmaps: 12,
  publishedRoadmaps: 8,
  draftRoadmaps: 4,
  totalViews: 1547,
  totalLikes: 328,
  totalNodes: 156,
};

export const MOCK_ROADMAPS: ContentManagerRoadmap[] = [
  {
    id: 1,
    subjectId: 1,
    title: 'React Fundamentals',
    description: 'Master the basics of React including components, hooks, and state management',
    subjectName: 'Frontend Development',
    version: 2,
    isLatest: true,
    status: 'Active',
    nodeCount: 24,
    createdAt: '2024-01-20T10:00:00Z',
    updatedAt: '2024-02-01T14:30:00Z',
  },
  {
    id: 2,
    subjectId: 1,
    title: 'Advanced TypeScript Patterns',
    description: 'Deep dive into advanced TypeScript patterns and best practices',
    subjectName: 'Frontend Development',
    version: 1,
    isLatest: true,
    status: 'Active',
    nodeCount: 18,
    createdAt: '2024-01-15T09:00:00Z',
    updatedAt: '2024-01-28T16:45:00Z',
  },
  {
    id: 3,
    subjectId: 1,
    title: 'Next.js App Router Guide',
    description: 'Complete guide to building applications with Next.js App Router',
    subjectName: 'Frontend Development',
    version: 1,
    isLatest: true,
    status: 'Draft',
    nodeCount: 15,
    createdAt: '2024-02-01T11:30:00Z',
    updatedAt: '2024-02-03T10:15:00Z',
  },
  {
    id: 4,
    subjectId: 1,
    title: 'CSS Grid & Flexbox Mastery',
    description: 'Learn modern CSS layout techniques with Grid and Flexbox',
    subjectName: 'Frontend Development',
    version: 1,
    isLatest: true,
    status: 'Active',
    nodeCount: 16,
    createdAt: '2024-01-10T08:00:00Z',
    updatedAt: '2024-01-25T13:20:00Z',
  },
  {
    id: 5,
    subjectId: 1,
    title: 'Web Performance Optimization',
    description: 'Techniques and strategies for optimizing web application performance',
    subjectName: 'Frontend Development',
    version: 2,
    isLatest: true,
    status: 'Active',
    nodeCount: 21,
    createdAt: '2024-01-08T15:00:00Z',
    updatedAt: '2024-01-30T09:40:00Z',
  },
  {
    id: 6,
    subjectId: 1,
    title: 'State Management with Zustand',
    description: 'Modern state management patterns using Zustand',
    subjectName: 'Frontend Development',
    version: 1,
    isLatest: true,
    status: 'Draft',
    nodeCount: 12,
    createdAt: '2024-01-28T14:00:00Z',
    updatedAt: '2024-02-02T11:25:00Z',
  },
  {
    id: 7,
    subjectId: 1,
    title: 'React Testing Library Guide',
    description: 'Comprehensive guide to testing React applications',
    subjectName: 'Frontend Development',
    version: 1,
    isLatest: true,
    status: 'Active',
    nodeCount: 15,
    createdAt: '2024-01-12T10:30:00Z',
    updatedAt: '2024-01-22T15:10:00Z',
  },
  {
    id: 8,
    subjectId: 1,
    title: 'Tailwind CSS Best Practices',
    description: 'Learn best practices and patterns for using Tailwind CSS',
    subjectName: 'Frontend Development',
    version: 1,
    isLatest: true,
    status: 'Draft',
    nodeCount: 10,
    createdAt: '2024-01-30T09:00:00Z',
    updatedAt: '2024-02-03T08:50:00Z',
  },
  {
    id: 9,
    subjectId: 1,
    title: 'React Fundamentals',
    description: 'Master the basics of React including components, hooks, and state management',
    subjectName: 'Frontend Development',
    version: 1,
    isLatest: false,
    status: 'Archived',
    nodeCount: 20,
    createdAt: '2024-01-20T10:00:00Z',
    updatedAt: '2024-01-20T10:00:00Z',
  },
];

export const MOCK_ROADMAP_VERSIONS: Record<number, RoadmapVersion[]> = {
  1: [
    {
      version: 2,
      publishedAt: '2024-02-01T14:30:00Z',
      changes: 'Added React 18 features and concurrent rendering',
    },
    {
      version: 1,
      publishedAt: '2024-01-20T10:00:00Z',
      changes: 'Initial release',
    },
  ],
  2: [
    {
      version: 1,
      publishedAt: '2024-01-15T09:00:00Z',
      changes: 'Initial release',
    },
  ],
};

// Comprehensive Roadmap Detail with Nodes and Edges
export const MOCK_ROADMAP_DETAIL: ContentManagerRoadmapDetail = {
  roadmap: {
    id: 1,
    subjectId: 1,
    title: 'React Fundamentals',
    description: 'Master the basics of React including components, hooks, and state management. This comprehensive roadmap will guide you through all essential React concepts.',
    createdById: 'cm-001',
    createdAt: '2024-01-20T10:00:00Z',
    version: 2,
    isLatest: true,
  },
  subjectName: 'Frontend Development',
  nodes: [
    {
      id: 1,
      roadmapId: 1,
      title: 'Introduction to React',
      description: 'Learn what React is, its benefits, and when to use it',
      difficulty: 'Beginner',
      orderNo: 1,
    },
    {
      id: 2,
      roadmapId: 1,
      title: 'JSX Fundamentals',
      description: 'Understanding JSX syntax and how it works',
      difficulty: 'Beginner',
      orderNo: 2,
    },
    {
      id: 3,
      roadmapId: 1,
      title: 'Components & Props',
      description: 'Building reusable components and passing data with props',
      difficulty: 'Beginner',
      orderNo: 3,
    },
    {
      id: 4,
      roadmapId: 1,
      title: 'State Management Basics',
      description: 'Learn how to manage component state with useState',
      difficulty: 'Intermediate',
      orderNo: 4,
    },
    {
      id: 5,
      roadmapId: 1,
      title: 'Event Handling',
      description: 'Handle user interactions and events in React',
      difficulty: 'Beginner',
      orderNo: 5,
    },
    {
      id: 6,
      roadmapId: 1,
      title: 'Conditional Rendering',
      description: 'Render components conditionally based on state',
      difficulty: 'Beginner',
      orderNo: 6,
    },
    {
      id: 7,
      roadmapId: 1,
      title: 'Lists and Keys',
      description: 'Rendering lists efficiently with keys',
      difficulty: 'Intermediate',
      orderNo: 7,
    },
    {
      id: 8,
      roadmapId: 1,
      title: 'Forms in React',
      description: 'Handle form inputs and controlled components',
      difficulty: 'Intermediate',
      orderNo: 8,
    },
    {
      id: 9,
      roadmapId: 1,
      title: 'useEffect Hook',
      description: 'Side effects and lifecycle with useEffect',
      difficulty: 'Intermediate',
      orderNo: 9,
    },
    {
      id: 10,
      roadmapId: 1,
      title: 'Custom Hooks',
      description: 'Create reusable logic with custom hooks',
      difficulty: 'Advanced',
      orderNo: 10,
    },
    {
      id: 11,
      roadmapId: 1,
      title: 'Context API',
      description: 'Share data across component tree without prop drilling',
      difficulty: 'Advanced',
      orderNo: 11,
    },
    {
      id: 12,
      roadmapId: 1,
      title: 'React Router',
      description: 'Navigation and routing in React applications',
      difficulty: 'Intermediate',
      orderNo: 12,
    },
  ],
  edges: [
    { id: 1, roadmapId: 1, fromNodeId: 1, toNodeId: 2, edgeType: 0, orderNo: 1 },
    { id: 2, roadmapId: 1, fromNodeId: 2, toNodeId: 3, edgeType: 0, orderNo: 2 },
    { id: 3, roadmapId: 1, fromNodeId: 3, toNodeId: 4, edgeType: 0, orderNo: 3 },
    { id: 4, roadmapId: 1, fromNodeId: 3, toNodeId: 5, edgeType: 0, orderNo: 4 },
    { id: 5, roadmapId: 1, fromNodeId: 4, toNodeId: 6, edgeType: 0, orderNo: 5 },
    { id: 6, roadmapId: 1, fromNodeId: 5, toNodeId: 6, edgeType: 0, orderNo: 6 },
    { id: 7, roadmapId: 1, fromNodeId: 6, toNodeId: 7, edgeType: 0, orderNo: 7 },
    { id: 8, roadmapId: 1, fromNodeId: 6, toNodeId: 8, edgeType: 0, orderNo: 8 },
    { id: 9, roadmapId: 1, fromNodeId: 7, toNodeId: 9, edgeType: 0, orderNo: 9 },
    { id: 10, roadmapId: 1, fromNodeId: 8, toNodeId: 9, edgeType: 0, orderNo: 10 },
    { id: 11, roadmapId: 1, fromNodeId: 9, toNodeId: 10, edgeType: 0, orderNo: 11 },
    { id: 12, roadmapId: 1, fromNodeId: 10, toNodeId: 11, edgeType: 1, orderNo: 12 },
    { id: 13, roadmapId: 1, fromNodeId: 11, toNodeId: 12, edgeType: 2, orderNo: 13 },
  ],
};

// Node Contents for each node
export const MOCK_NODE_CONTENTS: Record<number, NodeContentItemDTO[]> = {
  1: [
    {
      id: 1,
      nodeId: 1,
      contentType: 'Video',
      title: 'What is React? - Introduction',
      url: 'https://youtube.com/watch?v=example1',
      description: 'A beginner-friendly introduction to React and its core concepts',
      estimatedMinutes: 15,
      difficulty: 'Beginner',
      orderNo: 1,
      isRequired: true,
    },
    {
      id: 2,
      nodeId: 1,
      contentType: 'Documentation',
      title: 'React Official Documentation - Getting Started',
      url: 'https://react.dev/learn',
      description: 'Official React documentation for beginners',
      estimatedMinutes: 30,
      difficulty: 'Beginner',
      orderNo: 2,
      isRequired: true,
    },
    {
      id: 3,
      nodeId: 1,
      contentType: 'Article',
      title: 'Why Choose React in 2024',
      url: 'https://medium.com/example',
      description: 'Understand the benefits of using React',
      estimatedMinutes: 10,
      difficulty: 'Beginner',
      orderNo: 3,
      isRequired: false,
    },
  ],
  2: [
    {
      id: 4,
      nodeId: 2,
      contentType: 'Video',
      title: 'JSX Explained',
      url: 'https://youtube.com/watch?v=example2',
      description: 'Deep dive into JSX syntax and usage',
      estimatedMinutes: 20,
      difficulty: 'Beginner',
      orderNo: 1,
      isRequired: true,
    },
    {
      id: 5,
      nodeId: 2,
      contentType: 'Exercise',
      title: 'JSX Practice Exercises',
      url: 'https://codepen.io/example',
      description: 'Hands-on exercises to practice JSX',
      estimatedMinutes: 45,
      difficulty: 'Beginner',
      orderNo: 2,
      isRequired: true,
    },
  ],
  3: [
    {
      id: 6,
      nodeId: 3,
      contentType: 'Video',
      title: 'React Components Tutorial',
      url: 'https://youtube.com/watch?v=example3',
      description: 'Learn how to create functional components',
      estimatedMinutes: 25,
      difficulty: 'Beginner',
      orderNo: 1,
      isRequired: true,
    },
    {
      id: 7,
      nodeId: 3,
      contentType: 'Course',
      title: 'Component Composition Patterns',
      url: 'https://egghead.io/example',
      description: 'Advanced patterns for component composition',
      estimatedMinutes: 60,
      difficulty: 'Intermediate',
      orderNo: 2,
      isRequired: false,
    },
    {
      id: 8,
      nodeId: 3,
      contentType: 'Exercise',
      title: 'Build a Component Library',
      url: 'https://codesandbox.io/example',
      description: 'Create reusable components',
      estimatedMinutes: 90,
      difficulty: 'Intermediate',
      orderNo: 3,
      isRequired: true,
    },
  ],
  4: [
    {
      id: 9,
      nodeId: 4,
      contentType: 'Video',
      title: 'useState Hook Explained',
      url: 'https://youtube.com/watch?v=example4',
      description: 'Master the useState hook for state management',
      estimatedMinutes: 30,
      difficulty: 'Intermediate',
      orderNo: 1,
      isRequired: true,
    },
    {
      id: 10,
      nodeId: 4,
      contentType: 'Documentation',
      title: 'State Management Best Practices',
      url: 'https://react.dev/learn/state',
      description: 'Official guide on managing state',
      estimatedMinutes: 40,
      difficulty: 'Intermediate',
      orderNo: 2,
      isRequired: true,
    },
  ],
  5: [
    {
      id: 11,
      nodeId: 5,
      contentType: 'Video',
      title: 'Event Handling in React',
      url: 'https://youtube.com/watch?v=example5',
      description: 'Learn to handle events properly',
      estimatedMinutes: 20,
      difficulty: 'Beginner',
      orderNo: 1,
      isRequired: true,
    },
    {
      id: 12,
      nodeId: 5,
      contentType: 'Exercise',
      title: 'Interactive Event Examples',
      url: 'https://codepen.io/example',
      description: 'Practice handling various events',
      estimatedMinutes: 30,
      difficulty: 'Beginner',
      orderNo: 2,
      isRequired: true,
    },
  ],
};

export const MOCK_PAGINATED_RESPONSE = (pageIndex: number, pageSize: number): PaginatedResponse<ContentManagerRoadmap> => {
  const start = pageIndex * pageSize;
  const end = start + pageSize;
  const items = MOCK_ROADMAPS.slice(start, end);
  
  return {
    pageIndex,
    pageSize,
    totalPages: Math.ceil(MOCK_ROADMAPS.length / pageSize),
    totalCount: MOCK_ROADMAPS.length,
    hasPreviousPage: pageIndex > 0,
    hasNextPage: end < MOCK_ROADMAPS.length,
    items,
  };
};

export const MOCK_RECENT_ACTIVITIES = [
  {
    action: 'Published roadmap',
    target: 'React Fundamentals v2',
    time: '2 hours ago',
  },
  {
    action: 'Updated roadmap',
    target: 'Next.js App Router Guide',
    time: '5 hours ago',
  },
  {
    action: 'Created new roadmap',
    target: 'Tailwind CSS Best Practices',
    time: '1 day ago',
  },
  {
    action: 'Added node content',
    target: 'React Fundamentals - useState Hook',
    time: '2 days ago',
  },
  {
    action: 'Updated version',
    target: 'Web Performance Optimization v2',
    time: '3 days ago',
  },
];
